### ISSUE TITLE
Ask about some of your papers

### ISSUE THREAD

**Issue by LKHZ** [MicheleDelliVeneri/ALMASim#2]
Hello, I saw your article "**3D Detection and Characterization of ALMA Sources through DeepLearning**" on arxiv. I'm very interested in the method proposed in your article. I saw you provided the source code, but I can't open the website. I haven't seen it in your warehouse. Can you send me a link again? I'm looking forward to your reply!

**Comment by MicheleDelliVeneri** [comment]
Hi, both repositories related to the paper should be public. Also, both are still in the early stages of development regarding code readability, instructions and so on. Thank you for your interest in our article, I hope that you will find our code useful for your experiments. 
Cheers.

**Comment by LKHZ** [comment]
Hello, I try to open this link in your paper“[https://github.com/MicheleDelliVeneri/DeepFocus], but it cannot be opened. It seems that there are some problems. Do you have any good solutions? thank you

**Comment by MicheleDelliVeneri** [comment]
Hi, unfortunately, I cannot reproduce your issue. If I go to https://github.com/MicheleDelliVeneri/DeepFocus (which is the link in the paper) I get redirected to a public GitHub page. Maybe try to reset your browser cache and try again?

**Comment by LKHZ** [comment]
Hello, I don't understand a small problem in algorithm. In your paper "Frequency Detecting and Line Detection (5 - 7): bounding boxes around source candidates are used to extract dirty spectrum from the input cube", I am not too clear that dirty spectrum is the maximum value of bbox in each channel? Or can you point out where this part of the code is? https://github.com/MicheleDelliVeneri/DeepFocus

I look forward to your reply!


| |
孙利春
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/23/2022 16:42 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [MicheleDelliVeneri/ALMASim] Ask about some of your papers (Issue #2) |

Hi, unfortunately, I cannot reproduce your issue. If I go to https://github.com/MicheleDelliVeneri/DeepFocus (which is the link in the paper) I get redirected to a public GitHub page. Maybe try to reset your browser cache and try again?
